# HOW TO USE:
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -#
#   docker-compose -p dev_biometricscloud_backend -f dev.docker-compose.yml up   #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -#

version: '3.8'
services:
  app:
    container_name: htmltoimage_server_app
    stdin_open: true
    environment:
        HTMLTOIMAGE_SERVER_IP: 0.0.0.0
        HTMLTOIMAGE_SERVER_PORT: 8002
        HTMLTOIMAGE_SERVER_CHROME_HEADLESS_WS_URL: ws://browserless:9090
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    ports:
      - "8002:8002"
    depends_on:
      - browserless
    links:
      - browserless

  browserless:
    image: browserless/chrome:latest # https://hub.docker.com/r/browserless/chrome | https://docs.browserless.io/docs/docker.html
    environment:
      - DEBUG=browserless:*
      - MAX_CONCURRENT_SESSIONS=10
      - CONNECTION_TIMEOUT=60000
      - MAX_QUEUE_LENGTH=20
      - PREBOOT_CHROME=true
      - DEMO_MODE=false
      - HOST=0.0.0.0
      - ENABLE_DEBUGGER=false
      - PORT=9090
      - WORKSPACE_DELETE_EXPIRED=true
    container_name: "htmltoimage_server_browserless"
    restart: unless-stopped
