# HOW TO USE:
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -#
#   docker-compose -p dev_biometricscloud_backend -f dev.docker-compose.yml up   #
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -#

version: '3.8'
services:
  app:
    container_name: htmltoimage_server_app
    stdin_open: true
    environment:
        HTMLTOIMAGE_SERVER_ADDRESS: 0.0.0.0:8002
        HTMLTOIMAGE_SERVER_HOME_DIRECTORY_PATH: /data
        HTMLTOIMAGE_SERVER_CHROME_HEADLESS_WS_URL: ws://browserless:9090
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    # Connect the local filesystem with the docker filesystem.
    volumes:
      - ./data:/go/src/github.com/bartmika/htmltoimage-server/data
    restart: on-failure:10 # Notes via https://docs.docker.com/engine/reference/run/#restart-policies---restart
    depends_on:
      - browserless
    links:
      - browserless #links to browserless container

  browserless:
    image: browserless/chrome:latest # https://hub.docker.com/r/browserless/chrome
    environment:
      - DEBUG=browserless:*
      - MAX_CONCURRENT_SESSIONS=10
      - CONNECTION_TIMEOUT=60000
      - MAX_QUEUE_LENGTH=20
      - PREBOOT_CHROME=true
      - DEMO_MODE=false
      - HOST=0.0.0.0
      - ENABLE_DEBUGGER=false
      - PORT=9090
      - WORKSPACE_DELETE_EXPIRED=true
    container_name: "htmltoimage_server_browserless"
    restart: on-failure:10

# volumes:
#     htmltoimage_server_data:
