version: '3'

tasks:
  start:
    cmds:
      - docker-compose -p htmltoimage_server -f dev.docker-compose.yml up

  end:
    cmds:
      - docker-compose -p htmltoimage_server -f dev.docker-compose.yml down

  console:
    cmds:
      - docker exec -it htmltoimage_server bash

  deploy:
    cmds:
      - docker build -t bmika/htmltoimage-server:1.0 .
      - docker tag bmika/htmltoimage-server:1.0 bmika/htmltoimage-server:1.0
      - docker push bmika/htmltoimage-server:1.0

  # The following task will perform a vulnerability scan on our golang project and display any issues found.
  scan:
    cmds:
      - govulncheck ./...
      - trivy image bmika/htmltoimage-server:1.0
      - trivy repo https://github.com/bartmika/htmltoimage-server.git

  # The following command will upgade all the dependencies in this project.
  upgrade_dep:
    cmds:
      - go get -u ./...
      - go mod tidy
