version: '3'

tasks:
  start:
    cmds:
      - docker-compose -p htmltoimage_server -f dev.docker-compose.yml up

  end:
    cmds:
      - docker-compose -p htmltoimage_server -f dev.docker-compose.yml down

  console:
    cmds:
      - docker exec -it htmltoimage_server bash

  deploy:
    cmds:
      - docker build -f Dockerfile -t bartmika/htmltoimage-server:latest --platform linux/amd64 .
      - docker tag bartmika/htmltoimage-server:latest bartmika/htmltoimage-server:latest
      - docker push bartmika/htmltoimage-server:latest

  # The following task will perform a vulnerability scan on our golang project and display any issues found.
  scan:
    cmds:
      - govulncheck ./...
      - trivy image bartmika/htmltoimage-server:latest
      - trivy repo https://github.com/bartmika/htmltoimage-server.git

  # The following command will upgade all the dependencies in this project.
  upgrade_dep:
    cmds:
      - go get -u ./...
      - go mod tidy

  logout:
    cmds:
      - docker logout

  login:
    cmds:
      - docker login -u bartmika
